window.LingoData = window.LingoData || {};
window.LingoData.lesson10 = {
  id: 10,
  title: "Plural Possessives & Daily Life (Want/Have)",
  tier: "new",
  sections: [
    { heading: "Vocab — Family", note: "" },
    { heading: "Vocab — Other", note: "" },
    { heading: "Grammar — Plural Possessive Endings (on beet, \"house\")", note: "Our/Your(pl)/Their suffixes attached to a noun." },
    { heading: "Grammar — Exception: \"Dad\" & \"Brother\"", note: "Irregular possessive attachment to ab/akh. South forms are canonical; Lebanese forms (bayyi/bayyak/khayya/khayna) are a third dialect tier, distinct from the usual North/South split, and are captured as accepted alternates." },
    { heading: "Example Phrases — Possessive Pronouns", note: "" },
    { heading: "Example Phrases — Family Examples", note: "" },
    { heading: "Example Phrases — Saying \"Dad\" & Brother", note: "Standard (South) line paired with its Lebanese-dialect equivalent." },
    { heading: "Example Phrases — Connected Examples", note: "Appears only on the Example Phrases page, not repeated on the cheatsheet; included in full regardless." },
    { heading: "Example Phrases — Together Examples", note: "" },
    { heading: "Example Sentence Cheatsheet — Lesson 1", note: "" },
    { heading: "Vocab — Food & Drink", note: "" },
    { heading: "Vocab — Structure", note: "" },
    { heading: "Vocab — Synonyms", note: "" },
    { heading: "Grammar — \"To Want\" (bidd-, plural forms)", note: "" },
    { heading: "Grammar — \"To Have\" (3ind-, plural forms)", note: "" },
    { heading: "Example Phrases — To Want", note: "" },
    { heading: "Example Phrases — To Have", note: "" },
    { heading: "Example Phrases — Food & Drink", note: "" },
    { heading: "Example Phrases — Additional New Vocabulary", note: "New vocab (kanze, kanabaaye, Suufaaye, ooDet íl-2a3de, ooDet ín-noom) surfaced only in-context here, no standalone vocab card in source; captured as items regardless." },
    { heading: "Example Sentence Cheatsheet — Lesson 2", note: "" },
    { heading: "Conversation Group — \"Nice to Meet You\"", note: "Open/Response1/Response2 slot micro-dialogue. The نا (\"us\") plural ending is used even for one person; greeting does not change for feminine." },
    { heading: "Conversation Group — \"Goodnight\"", note: "Open/Response1/Response2 slot micro-dialogue. Feminine open: tíSba7i; plural open: tíSba7u. Response 2 is the more poetic alternate reply." },
    { heading: "Group Exercise", note: "Visual noun-prompt exercise (possessive endings, idafa construction, and illi drills) with no text answer key in source — represented as description, not Items, consistent with prior lessons. Objects/places: balad, wilaaye, madiine (reused from Lesson 9 geography, not new here), 2ahwe, shaay, may, ooDa/ghirfe, akíl. People/family: 3eele, ahíl, wlaad, banaat, ab, um/ím, íbín, bínt, akh, ukht/íkht, zooj (\"husband\"), mara (\"wife\"). zooj and mara are new words appearing only in this visual prompt with no standalone card elsewhere, so — per the no-answer-key visual-prompt handling — they are noted here rather than converted into Items." }
  ],
  items: [
    // ---------- VOCAB ----------
    { id: "l10-v-001", lessonId: 10, type: "vocab", arabic: "أُم", romanization: "um", altRomanizations: ["ím"], english: "mother", direction: "both", grammarNote: null },
    { id: "l10-v-002", lessonId: 10, type: "vocab", arabic: "أب", romanization: "ab", altRomanizations: [], english: "father", direction: "both", grammarNote: null },
    { id: "l10-v-003", lessonId: 10, type: "vocab", arabic: "بِنت", romanization: "bínt", altRomanizations: [], english: "daughter", direction: "both", grammarNote: null },
    { id: "l10-v-004", lessonId: 10, type: "vocab", arabic: "إِبن", romanization: "íbín", altRomanizations: [], english: "son", direction: "both", grammarNote: null },
    { id: "l10-v-005", lessonId: 10, type: "vocab", arabic: "أُخت", romanization: "ukht", altRomanizations: ["íkht"], english: "sister", direction: "both", grammarNote: null },
    { id: "l10-v-006", lessonId: 10, type: "vocab", arabic: "أخ", romanization: "akh", altRomanizations: [], english: "brother", direction: "both", grammarNote: null },
    { id: "l10-v-007", lessonId: 10, type: "vocab", arabic: "مَع بَعض", romanization: "ma3 ba3D", altRomanizations: [], english: "together", direction: "both", grammarNote: null },
    { id: "l10-v-008", lessonId: 10, type: "vocab", arabic: "عَمّان", romanization: "3ammaan", altRomanizations: [], english: "Amman, Jordan", direction: "both", grammarNote: null },
    { id: "l10-v-009", lessonId: 10, type: "vocab", arabic: "شاي", romanization: "shaay", altRomanizations: [], english: "tea", direction: "both", grammarNote: null },
    { id: "l10-v-010", lessonId: 10, type: "vocab", arabic: "أكِل", romanization: "akíl", altRomanizations: [], english: "food", direction: "both", grammarNote: null },
    { id: "l10-v-011", lessonId: 10, type: "vocab", arabic: "جُوعان", romanization: "juu3aan", altRomanizations: [], english: "hungry", direction: "both", grammarNote: null },
    { id: "l10-v-012", lessonId: 10, type: "vocab", arabic: "قَهوة", romanization: "2ahwe", altRomanizations: [], english: "coffee", direction: "both", grammarNote: null },
    { id: "l10-v-013", lessonId: 10, type: "vocab", arabic: "مَيْ", romanization: "may", altRomanizations: [], english: "water", direction: "both", grammarNote: null },
    { id: "l10-v-014", lessonId: 10, type: "vocab", arabic: "عَطشان", romanization: "3aTshaan", altRomanizations: [], english: "thirsty", direction: "both", grammarNote: null },
    { id: "l10-v-015", lessonId: 10, type: "vocab", arabic: "كتير", romanization: "ktiir", altRomanizations: [], english: "very, a lot", direction: "both", grammarNote: null },
    { id: "l10-v-016", lessonId: 10, type: "vocab", arabic: "إللي", romanization: "ílli", altRomanizations: [], english: "who is, that is", direction: "both", grammarNote: "Relative pronoun \"who/that/which\" — introduces a relative clause (e.g. íS-Sabi ílli laabís kanze... = \"the boy who is wearing a shirt...\"). Invariant: does not change for gender, number, or case." },
    { id: "l10-v-017", lessonId: 10, type: "vocab", arabic: "يا", romanization: "ya", altRomanizations: [], english: "oh", direction: "both", grammarNote: null },
    { id: "l10-v-018", lessonId: 10, type: "vocab", arabic: "شُكراً", romanization: "shukran", altRomanizations: [], english: "thank you", direction: "both", grammarNote: null },
    { id: "l10-v-019", lessonId: 10, type: "vocab", arabic: "صَبِيّة", romanization: "Sabiyye", altRomanizations: [], english: "young lady", direction: "both", grammarNote: "Synonym of بِنت (bínt, \"daughter/girl\")." },
    { id: "l10-v-020", lessonId: 10, type: "vocab", arabic: "صَبي", romanization: "Sabi", altRomanizations: [], english: "boy", direction: "both", grammarNote: "Synonym of وَلَد (wálad, \"boy/kid\")." },
    { id: "l10-v-021", lessonId: 10, type: "vocab", arabic: "أوضَة", romanization: "ooDa", altRomanizations: ["uuDa", "ghirfe"], english: "room", direction: "both", grammarNote: "ooDa (S) / uuDa (N) are dialect variants of the same word. غِرفة (ghirfe) is a separate root word that is a full synonym for \"room\" (not a North/South variant) — also accepted." },
    { id: "l10-v-022", lessonId: 10, type: "vocab", arabic: "كَنزة", romanization: "kanze", altRomanizations: [], english: "shirt, sweater", direction: "both", grammarNote: null },
    { id: "l10-v-023", lessonId: 10, type: "vocab", arabic: "كَنابايَة", romanization: "kanabaaye", altRomanizations: [], english: "couch", direction: "both", grammarNote: null },
    { id: "l10-v-024", lessonId: 10, type: "vocab", arabic: "صُوفايَة", romanization: "Suufaaye", altRomanizations: [], english: "sofa, couch", direction: "both", grammarNote: "Distinct word used alongside كَنابايَة (kanabaaye) for \"couch\" — a full synonym, not a dialect variant." },
    { id: "l10-v-025", lessonId: 10, type: "vocab", arabic: "أوضِة القَعدة", romanization: "ooDet íl-2a3de", altRomanizations: ["2a3de"], english: "living room (lit. \"sitting room\")", direction: "both", grammarNote: null },
    { id: "l10-v-026", lessonId: 10, type: "vocab", arabic: "أوضِة النَّوم", romanization: "ooDet ín-noom", altRomanizations: [], english: "bedroom (lit. \"sleep room\")", direction: "both", grammarNote: null },

    // ---------- GRAMMAR ----------
    { id: "l10-g-001", lessonId: 10, type: "grammar", arabic: "بيتنا", romanization: "beetna", altRomanizations: [], english: "our house", direction: "both", grammarNote: "Plural possessive suffix -na = \"our\", attached directly to the noun (بيت + نا). Identical in South and North dialects." },
    { id: "l10-g-002", lessonId: 10, type: "grammar", arabic: "بيتكُم", romanization: "beetkum", altRomanizations: ["beetkun"], english: "your (pl) house", direction: "both", grammarNote: "Plural possessive suffix -kum (South) / -kun (North) = \"your (plural)\", attached to the noun." },
    { id: "l10-g-003", lessonId: 10, type: "grammar", arabic: "بيتهُم", romanization: "beethum", altRomanizations: ["beetun"], english: "their house", direction: "both", grammarNote: "Plural possessive suffix -hum (South) / -un (North) = \"their\", attached to the noun." },
    { id: "l10-g-004", lessonId: 10, type: "grammar", arabic: "أبوي", romanization: "abuwi", altRomanizations: ["bayyi"], english: "my dad", direction: "both", grammarNote: "Irregular possessive attachment to أب (\"dad/father\") — does not take the regular suffix pattern. South (canonical): abuwi. Lebanese — a third dialect tier distinct from the usual North/South split: bayyi." },
    { id: "l10-g-005", lessonId: 10, type: "grammar", arabic: "أبوك", romanization: "abuuk", altRomanizations: ["bayyak"], english: "your (m) dad", direction: "both", grammarNote: "Irregular \"dad\" possessive, 2nd person masculine. South (canonical): abuuk. Lebanese (third dialect tier): bayyak." },
    { id: "l10-g-006", lessonId: 10, type: "grammar", arabic: "أخُوها", romanization: "akhuuha", altRomanizations: ["khayya"], english: "her brother", direction: "both", grammarNote: "Irregular possessive attachment to أخ (\"brother\"). South (canonical): akhuuha. Lebanese (third dialect tier): khayya." },
    { id: "l10-g-007", lessonId: 10, type: "grammar", arabic: "أخُونا", romanization: "akhuuna", altRomanizations: ["khayna"], english: "our brother", direction: "both", grammarNote: "Irregular \"brother\" possessive, plural \"our\". South (canonical): akhuuna. Lebanese (third dialect tier): khayna." },
    { id: "l10-g-008", lessonId: 10, type: "grammar", arabic: "بِدنا", romanization: "bídna", altRomanizations: [], english: "we want", direction: "both", grammarNote: "Plural \"to want\" (bidd-) conjugation, 1st person plural. Identical in South and North." },
    { id: "l10-g-009", lessonId: 10, type: "grammar", arabic: "بِدكُم", romanization: "bídkum", altRomanizations: ["bídkun"], english: "you (pl) want", direction: "both", grammarNote: "Plural \"to want\" conjugation, 2nd person plural. South: bídkum. North: bídkun." },
    { id: "l10-g-010", lessonId: 10, type: "grammar", arabic: "بِدهُم", romanization: "bídhum", altRomanizations: ["bíddun"], english: "they want", direction: "both", grammarNote: "Plural \"to want\" conjugation, 3rd person plural. South: bídhum. North: bíddun." },
    { id: "l10-g-011", lessonId: 10, type: "grammar", arabic: "عِنّا", romanization: "3ínna", altRomanizations: [], english: "we have", direction: "both", grammarNote: "Plural \"to have\" (3ind-) conjugation, 1st person plural. Identical in South and North." },
    { id: "l10-g-012", lessonId: 10, type: "grammar", arabic: "عِندكُم", romanization: "3índkum", altRomanizations: ["3índkun"], english: "you (pl) have", direction: "both", grammarNote: "Plural \"to have\" conjugation, 2nd person plural. South: 3índkum. North: 3índkun." },
    { id: "l10-g-013", lessonId: 10, type: "grammar", arabic: "عِندهُم", romanization: "3índhum", altRomanizations: ["3índun"], english: "they have", direction: "both", grammarNote: "Plural \"to have\" conjugation, 3rd person plural. South: 3índhum. North: 3índun." },

    // ---------- PHRASES ----------
    { id: "l10-p-001", lessonId: 10, type: "phrase", arabic: "أهِلكُم جايِين لَهون؟", romanization: "ahílkum jaayiin la-hoon?", altRomanizations: [], english: "Are your (pl) parents coming here?", direction: "both", grammarNote: null },
    { id: "l10-p-002", lessonId: 10, type: "phrase", arabic: "عيلتنا مِن لِبنان.", romanization: "3eelítna mín líbnaan.", altRomanizations: [], english: "Our family is from Lebanon.", direction: "both", grammarNote: null },
    { id: "l10-p-003", lessonId: 10, type: "phrase", arabic: "ولادهُم نايِمِين فِالسَّيّارَة.", romanization: "wlaadhum naaymiin fis-sayyaara.", altRomanizations: [], english: "Their kids are sleeping in the car.", direction: "both", grammarNote: null },
    { id: "l10-p-004", lessonId: 10, type: "phrase", arabic: "مَدينتُن صَغيرة.", romanization: "madiintun zghiire.", altRomanizations: [], english: "Their city is small.", direction: "both", grammarNote: null },
    { id: "l10-p-005", lessonId: 10, type: "phrase", arabic: "أهِلكُن جُوّا البيت؟", romanization: "ahílkun juwwa íl-beet?", altRomanizations: [], english: "Are your (pl) parents inside the house?", direction: "both", grammarNote: null },
    { id: "l10-p-006", lessonId: 10, type: "phrase", arabic: "إمُّن مِش هون. هيّ بِالشِّغِل.", romanization: "ímmun mísh hoon. hiyye bísh-shíghíl.", altRomanizations: [], english: "Their mother isn't here. She's at work.", direction: "both", grammarNote: null },
    { id: "l10-p-007", lessonId: 10, type: "phrase", arabic: "إبنكُم فِالمَدرَسة؟", romanization: "íbínkum fil-madrase?", altRomanizations: [], english: "Is your son at school?", direction: "both", grammarNote: null },
    { id: "l10-p-008", lessonId: 10, type: "phrase", arabic: "شُو إسِم بِنتُن؟", romanization: "shu ísím bíntun?", altRomanizations: [], english: "What's their daughter's name?", direction: "both", grammarNote: null },
    { id: "l10-p-009", lessonId: 10, type: "phrase", arabic: "أُختنا ساكِنة فِمَدينة عَمّان.", romanization: "ukhtna saakne fi-madiinet 3ammaan.", altRomanizations: [], english: "Our sister lives in the city of Amman.", direction: "both", grammarNote: null },
    { id: "l10-p-010", lessonId: 10, type: "phrase", arabic: "أخُوك هون؟ لاء، هُوّ فِالبيت.", romanization: "akhuuk hoon? la2, huwwe fíl-beet.", altRomanizations: [], english: "Is your (m) brother here? No, he is at home.", direction: "both", grammarNote: "Standard (South) line. See l10-p-011 for the Lebanese-dialect equivalent." },
    { id: "l10-p-011", lessonId: 10, type: "phrase", arabic: "خَيَّك هون؟ لاء، هُوّ بِلبيت.", romanization: "khayyak hoon? la2, huwwe bíl-bayt.", altRomanizations: [], english: "Is your (m) brother here? No, he is at home.", direction: "both", grammarNote: "Lebanese-dialect equivalent of l10-p-010, using the khayyak Dad/Brother exception form." },
    { id: "l10-p-012", lessonId: 10, type: "phrase", arabic: "أبُوي مِن سُورية، بَس إمّي مِن فَلَسطين.", romanization: "abuwi mín suurya, bas ímmi mín falasTiin.", altRomanizations: [], english: "My dad is from Syria, but my mom is from Palestine.", direction: "both", grammarNote: "Standard (South) line. See l10-p-013 for the Lebanese-dialect equivalent." },
    { id: "l10-p-013", lessonId: 10, type: "phrase", arabic: "بَيّي مِن لبنان، بَس إمّي مِن فَلَسطين.", romanization: "bayyi mín líbnaan, bas ímmi mín falasTiin.", altRomanizations: [], english: "My dad is from Lebanon, but my mom is from Palestine.", direction: "both", grammarNote: "Lebanese-dialect equivalent of l10-p-012, using the bayyi Dad exception form." },
    { id: "l10-p-014", lessonId: 10, type: "phrase", arabic: "أخُو البِنت عايِش فِأمريكا مَع أبُوه.", romanization: "akhu íl-bint 3aayish fi-amriika ma3 abuuh.", altRomanizations: [], english: "The girl's brother is living in America with his dad.", direction: "both", grammarNote: "Standard (South) line. See l10-p-015 for the Lebanese-dialect equivalent." },
    { id: "l10-p-015", lessonId: 10, type: "phrase", arabic: "خَيْ البِنت، عايِش بِأمريكا مَع بَيُّه.", romanization: "khay íl-bint 3aayish bi-amriika ma3 bayyu.", altRomanizations: [], english: "The girl's brother is living in America with his dad.", direction: "both", grammarNote: "Lebanese-dialect equivalent of l10-p-014." },
    { id: "l10-p-016", lessonId: 10, type: "phrase", arabic: "كِيفُن؟", romanization: "kiifun?", altRomanizations: [], english: "How are they?", direction: "both", grammarNote: null },
    { id: "l10-p-017", lessonId: 10, type: "phrase", arabic: "وينكُم؟", romanization: "weenkum?", altRomanizations: [], english: "Where are you (pl)?", direction: "both", grammarNote: null },
    { id: "l10-p-018", lessonId: 10, type: "phrase", arabic: "إحنا مَعْهُم فِالمَطعَم.", romanization: "í7na ma3hum fil-maT3am.", altRomanizations: [], english: "We are with them at the restaurant.", direction: "both", grammarNote: null },
    { id: "l10-p-019", lessonId: 10, type: "phrase", arabic: "كِلنا رايحِين.", romanization: "kilna raayhiin.", altRomanizations: [], english: "All of us are going.", direction: "both", grammarNote: null },
    { id: "l10-p-020", lessonId: 10, type: "phrase", arabic: "كُلنا ساكِنين مَع بَعض.", romanization: "kulna saaknriin ma3 ba3D.", altRomanizations: [], english: "We all live together.", direction: "both", grammarNote: null },
    { id: "l10-p-021", lessonId: 10, type: "phrase", arabic: "كيفَك؟ كُلُّه تَمام.", romanization: "kiifak? kullu tamaam.", altRomanizations: [], english: "How are you? Everything is fine.", direction: "both", grammarNote: null },
    { id: "l10-p-022", lessonId: 10, type: "phrase", arabic: "أبُوي وأُمّي مِش مَع بَعض.", romanization: "abuwi u-ummi mísh ma3 ba3D.", altRomanizations: [], english: "My dad and mom are not together.", direction: "both", grammarNote: null },
    { id: "l10-p-023", lessonId: 10, type: "phrase", arabic: "بَناتنا مَع بَعض فِالمَدرَسة.", romanization: "banaatna ma3 ba3D fil-madrase.", altRomanizations: [], english: "Our daughters are together at school.", direction: "both", grammarNote: null },
    { id: "l10-p-024", lessonId: 10, type: "phrase", arabic: "هِنّ عايِشِين مَع بَعض.", romanization: "hínne 3aayshiin ma3 ba3D.", altRomanizations: [], english: "They are living together.", direction: "both", grammarNote: null },
    { id: "l10-p-025", lessonId: 10, type: "phrase", arabic: "بِدنا شاي!", romanization: "bídna shaay!", altRomanizations: [], english: "We want tea!", direction: "both", grammarNote: null },
    { id: "l10-p-026", lessonId: 10, type: "phrase", arabic: "بِدكُم قَهوة؟ لاء، شُكراً.", romanization: "bídkum 2ahwe? la2, shukran.", altRomanizations: [], english: "Do you (pl) want coffee? No, thanks.", direction: "both", grammarNote: null },
    { id: "l10-p-027", lessonId: 10, type: "phrase", arabic: "أهلي بِدُّن سَيّارَة جِديدة.", romanization: "ahli bíddun sayyaara jdiide.", altRomanizations: [], english: "My parents want a new car.", direction: "both", grammarNote: null },
    { id: "l10-p-028", lessonId: 10, type: "phrase", arabic: "عَنّا أكِل فِالبيت.", romanization: "3anna akíl fíl-beet.", altRomanizations: [], english: "We have food at home.", direction: "both", grammarNote: null },
    { id: "l10-p-029", lessonId: 10, type: "phrase", arabic: "أنا عَطشان، عَندكُن مَي؟", romanization: "ana 3aTshaan, 3andkun may?", altRomanizations: [], english: "I'm thirsty, do you (pl) have water?", direction: "both", grammarNote: null },
    { id: "l10-p-030", lessonId: 10, type: "phrase", arabic: "عِندهُم سَيّارَة، بَس سَيّارتهُم قَديمة.", romanization: "3índhum sayyaara, bas sayyaarthum 2adiime.", altRomanizations: [], english: "They have a car, but their car is old.", direction: "both", grammarNote: null },
    { id: "l10-p-031", lessonId: 10, type: "phrase", arabic: "إنتي عَطشانة؟ اي، بِدّي مَي.", romanization: "ínti 3aTshaane? ee, bíddi may.", altRomanizations: [], english: "Are you (f) thirsty? Yes, I want water.", direction: "both", grammarNote: null },
    { id: "l10-p-032", lessonId: 10, type: "phrase", arabic: "هيّ جُوعانة؟ لاء، عِندها أكِل.", romanization: "hiyye juu3aane? la2, 3índha akíl.", altRomanizations: [], english: "Is she hungry? No, she has food.", direction: "both", grammarNote: null },
    { id: "l10-p-033", lessonId: 10, type: "phrase", arabic: "عِندي مَي. أنا مِش عَطشان.", romanization: "3índi may. ana mísh 3aTshaan.", altRomanizations: [], english: "I have water. I am not thirsty.", direction: "both", grammarNote: null },
    { id: "l10-p-034", lessonId: 10, type: "phrase", arabic: "أنا جُوعان. في أكِل هون؟", romanization: "ana juu3aan. fii akíl hoon?", altRomanizations: [], english: "I am hungry. Is there food here?", direction: "both", grammarNote: null },
    { id: "l10-p-035", lessonId: 10, type: "phrase", arabic: "صَباح الخير ماما، بِدِّك قَهوة؟", romanization: "Sabaa7 il-kheer maama, bíddek 2ahwe?", altRomanizations: [], english: "Good morning mom, do you (f) want coffee?", direction: "both", grammarNote: null },
    { id: "l10-p-036", lessonId: 10, type: "phrase", arabic: "لاء، يا إبني، بِدّي شاي.", romanization: "la2, ya íbni, bíddi shaay.", altRomanizations: [], english: "No, my son, I want tea.", direction: "both", grammarNote: null },
    { id: "l10-p-037", lessonId: 10, type: "phrase", arabic: "الصَّبِيّة جُوعانة. بِدها أكِل.", romanization: "íS-Sabiyye juu3aane. bídha akíl.", altRomanizations: ["bídda akíl"], english: "The young lady is hungry. She wants food.", direction: "both", grammarNote: null },
    { id: "l10-p-038", lessonId: 10, type: "phrase", arabic: "اي، عِنّا ولاد، عِنّا صَبي وبِنت.", romanization: "ee, 3ínna wlaad, 3ínna Sabi u-bínt.", altRomanizations: [], english: "Yes, we have kids, we have a boy and a girl.", direction: "both", grammarNote: null },
    { id: "l10-p-039", lessonId: 10, type: "phrase", arabic: "الصَّبي إللي لابِس كَنزة زَرقَة كتير تَعبان.", romanization: "íS-Sabi ílli laabís kanze zar2a ktiir ta3baan.", altRomanizations: [], english: "The boy that's wearing a blue t-shirt is very tired.", direction: "both", grammarNote: "Example of íllí (relative pronoun, l10-v-016) introducing a relative clause." },
    { id: "l10-p-040", lessonId: 10, type: "phrase", arabic: "الصَّبِيّة إللي فِالسَّيّارَة هناك، حِلوة كتير.", romanization: "íS-Sabiyye ílli fis-sayyaara hnaak, 7ilwe ktiir.", altRomanizations: [], english: "The young lady that's in the car over there is very pretty.", direction: "both", grammarNote: "Example of íllí (relative pronoun, l10-v-016) introducing a relative clause." },
    { id: "l10-p-041", lessonId: 10, type: "phrase", arabic: "الكَلب إللي فِالبيت كتير كِبير.", romanization: "íl-kalb ílli fíl-beet ktiir kbiir.", altRomanizations: [], english: "The dog that's in the house is very big.", direction: "both", grammarNote: "Example of íllí (relative pronoun, l10-v-016) introducing a relative clause." },
    { id: "l10-p-042", lessonId: 10, type: "phrase", arabic: "الأوضَة إللي هنيك كتير كِبيرة.", romanization: "íl-uuDa ílli hniik ktiir kbiire.", altRomanizations: [], english: "The room that's over there is very big.", direction: "both", grammarNote: "Example of íllí (relative pronoun, l10-v-016) introducing a relative clause." },
    { id: "l10-p-043", lessonId: 10, type: "phrase", arabic: "عِنّا كَنابايَة سودا فِأوضِة القَعدة.", romanization: "3ínna kanabaaye sooda fi-ooDet íl-2a3de.", altRomanizations: [], english: "We have a black couch in the living room.", direction: "both", grammarNote: null },
    { id: "l10-p-044", lessonId: 10, type: "phrase", arabic: "ما بِدُّن الصُّوفايَة إللي بِأوضِة النَّوم.", romanization: "maa bíddun íS-Suufaaye ílli bi-uuDet ín-noom.", altRomanizations: [], english: "They don't want the couch that's in the bed room.", direction: "both", grammarNote: "Example of íllí (relative pronoun, l10-v-016) introducing a relative clause." },
    { id: "l10-p-045", lessonId: 10, type: "phrase", arabic: "تشَرَّفنا", romanization: "tsharrafna", altRomanizations: [], english: "Pleasure to meet you (lit. \"you honor us\")", direction: "both", grammarNote: "The نا (\"us\") plural ending is used even when addressing/speaking about just one person; the greeting does not change for feminine." },
    { id: "l10-p-046", lessonId: 10, type: "phrase", arabic: "الشَّرَف إلي", romanization: "ísh-sharaf íli", altRomanizations: [], english: "The pleasure is mine (lit. \"the honor to me\")", direction: "both", grammarNote: null },
    { id: "l10-p-047", lessonId: 10, type: "phrase", arabic: "تشَرَّفنا (أكتَر)", romanization: "tsharrafna aktar", altRomanizations: [], english: "Pleasure to meet you (more) (lit. \"you honor us (more)\")", direction: "both", grammarNote: null },
    { id: "l10-p-048", lessonId: 10, type: "phrase", arabic: "تِصبَح على خير", romanization: "tíSba7 3ala kheer", altRomanizations: ["tísba7i", "tísba7u"], english: "Goodnight (m) (lit. \"may you wake up in goodness\")", direction: "both", grammarNote: "Feminine form: tísba7i. Plural form: tísba7u." },
    { id: "l10-p-049", lessonId: 10, type: "phrase", arabic: "وإنت بخير", romanization: "w-ínta b-kheer", altRomanizations: [], english: "Goodnight to you (lit. \"and you in goodness\")", direction: "both", grammarNote: null },
    { id: "l10-p-050", lessonId: 10, type: "phrase", arabic: "وإنت مِن أهلُه", romanization: "w-ínte mín ahlu", altRomanizations: [], english: "And may you be good", direction: "both", grammarNote: "The second and more poetic of the two Goodnight responses; literally \"and may you be from the family of goodness.\"" },

    // ---------- SENTENCES (Cheatsheet) ----------
    { id: "l10-s-001", lessonId: 10, type: "sentence", arabic: "أهِلكُم جايِين لَهون؟", romanization: "ahílkum jaayiin la-hoon?", altRomanizations: [], english: "Are your (p) parents coming here?", direction: "both", grammarNote: null },
    { id: "l10-s-002", lessonId: 10, type: "sentence", arabic: "ولادهُم نايِمِين فِالسَّيّارَة.", romanization: "wlaadhum naaymiin fis-sayyaara.", altRomanizations: [], english: "Their kids are sleeping in the car.", direction: "both", grammarNote: null },
    { id: "l10-s-003", lessonId: 10, type: "sentence", arabic: "عيلتنا مِن لِبنان.", romanization: "3eelítna mín líbnaan.", altRomanizations: [], english: "Our family is from Lebanon.", direction: "both", grammarNote: null },
    { id: "l10-s-004", lessonId: 10, type: "sentence", arabic: "أهِلكُن جُوّا البيت؟", romanization: "ahílkun juwwa íl-beet?", altRomanizations: [], english: "Are your parents inside the house?", direction: "both", grammarNote: null },
    { id: "l10-s-005", lessonId: 10, type: "sentence", arabic: "مَدينتُن صَغيرة.", romanization: "madiintun zghiire.", altRomanizations: [], english: "Their city is small.", direction: "both", grammarNote: null },
    { id: "l10-s-006", lessonId: 10, type: "sentence", arabic: "إمُّن مِش هون. هيّ بِالشِّغِل.", romanization: "ímmun mísh hoon. hiyye bísh-shíghíl.", altRomanizations: [], english: "Their mother isn't here. She's at work.", direction: "both", grammarNote: null },
    { id: "l10-s-007", lessonId: 10, type: "sentence", arabic: "إبنكُم فِالمَدرَسة؟", romanization: "íbínkum fil-madrase?", altRomanizations: [], english: "Is your son at school?", direction: "both", grammarNote: null },
    { id: "l10-s-008", lessonId: 10, type: "sentence", arabic: "شُو إسِم بِنتُن؟", romanization: "shu ísím bíntun?", altRomanizations: [], english: "What's their daughter's name?", direction: "both", grammarNote: null },
    { id: "l10-s-009", lessonId: 10, type: "sentence", arabic: "أُختنا ساكِنة فِمَدينة عَمّان.", romanization: "ukhtna saakne fi-madiinet 3ammaan.", altRomanizations: [], english: "Our sister lives in the city of Amman.", direction: "both", grammarNote: null },
    { id: "l10-s-010", lessonId: 10, type: "sentence", arabic: "أخُوك هون؟ لاء، هُوّا فِالبيت.", romanization: "akhuuk hoon? la2, huwwa fíl-beet.", altRomanizations: ["khayyak hawn? la2, huwwe bíl-bayt."], english: "Is your (m) brother here? No, he is at home.", direction: "both", grammarNote: "Standard (South) line is romanization; Lebanese equivalent (khayyak hawn? la2, huwwe bíl-bayt.) is the altRomanization — a distinct dialect tier, not just a spelling variant. Source also spells \"he\" as huwwe on the Example Phrases page vs. huwwa here." },
    { id: "l10-s-011", lessonId: 10, type: "sentence", arabic: "أبُوي مِن سُورية، بَس أُمّي مِن فَلَسطين.", romanization: "abuwi mín suurya, bas ummi mín falasTiin.", altRomanizations: ["bayye mín libneen, bas ímmi mín falasTiin."], english: "My dad is from Syria, and my mom is from Palestine.", direction: "both", grammarNote: "This English gloss reflects only the Standard (South) line, per the source. The Lebanese altRomanization line changes \"Syria\" to \"Lebanon,\" but the cheatsheet gives only one translation for both — see l10-p-013 for a corrected, Lebanese-specific gloss." },
    { id: "l10-s-012", lessonId: 10, type: "sentence", arabic: "أخُو البِنت عايِش فِأمريكا مَع أبُوه.", romanization: "akhu íl-bínt 3aayísh fi-amriika ma3 abuuh.", altRomanizations: ["khay íl-bint 3aayísh bi-amriika ma3 bayyo."], english: "The girl's brother is living in the USA with his dad.", direction: "both", grammarNote: "Standard (South) line is romanization; Lebanese equivalent is the altRomanization (bayyo/bayyu spelling variant vs. the Example Phrases page)." },
    { id: "l10-s-013", lessonId: 10, type: "sentence", arabic: "أبُوي وأُمّي مِش مَع بَعض.", romanization: "abuwi u-ummi mísh ma3 ba3D.", altRomanizations: [], english: "My dad, and mom are not together.", direction: "both", grammarNote: null },
    { id: "l10-s-014", lessonId: 10, type: "sentence", arabic: "بَناتنا مَع بَعض فِالمَدرَسة.", romanization: "banaatna ma3 ba3D fil-madrase.", altRomanizations: [], english: "Our daughters are together at school.", direction: "both", grammarNote: null },
    { id: "l10-s-015", lessonId: 10, type: "sentence", arabic: "هِنّ عايِشِين مَع بَعض.", romanization: "hínne 3aayshiin ma3 ba3d.", altRomanizations: [], english: "They are living together.", direction: "both", grammarNote: null },
    { id: "l10-s-016", lessonId: 10, type: "sentence", arabic: "بِدنا شاي!", romanization: "bídna shaay!", altRomanizations: [], english: "We want tea.", direction: "both", grammarNote: null },
    { id: "l10-s-017", lessonId: 10, type: "sentence", arabic: "بِدكُم قَهوة؟ لاء شُكراً.", romanization: "bídkum 2ahwe? la2 shukran.", altRomanizations: [], english: "Do you (p) want coffee? No, thanks.", direction: "both", grammarNote: null },
    { id: "l10-s-018", lessonId: 10, type: "sentence", arabic: "أهلي بِدُّن سَيّارَة جِديدة.", romanization: "ahli bíddun sayyaara jdiide.", altRomanizations: [], english: "My parents want a new car.", direction: "both", grammarNote: null },
    { id: "l10-s-019", lessonId: 10, type: "sentence", arabic: "عَنّا أكِل فِالبيت.", romanization: "3anna akíl fíl-beet.", altRomanizations: [], english: "We have food at home.", direction: "both", grammarNote: null },
    { id: "l10-s-020", lessonId: 10, type: "sentence", arabic: "أنا عَطشان، عَندكُن مَي؟", romanization: "ana 3aTshaan, 3andkun maay?", altRomanizations: [], english: "I am thirsty, Do you (p) have water?", direction: "both", grammarNote: null },
    { id: "l10-s-021", lessonId: 10, type: "sentence", arabic: "عِندهُم سَيّارَة، بَس سَيّارِتهُم قَديمة.", romanization: "3índhum sayyaara, bas sayyaaríthum 2adiime.", altRomanizations: [], english: "They have a car, but their car is old.", direction: "both", grammarNote: null },
    { id: "l10-s-022", lessonId: 10, type: "sentence", arabic: "إنتي عَطشانة؟ اي، بِدّي مَي.", romanization: "ínti 3aTshaane? ee, bíddi may.", altRomanizations: [], english: "Are you (f) thirsty? yes, I want water.", direction: "both", grammarNote: null },
    { id: "l10-s-023", lessonId: 10, type: "sentence", arabic: "هيّ جُوعانة؟ لاء، عِندها أكِل.", romanization: "hiyye juu3aane? la2, 3índha akíl.", altRomanizations: [], english: "Is she hungry? No, she has food.", direction: "both", grammarNote: null },
    { id: "l10-s-024", lessonId: 10, type: "sentence", arabic: "عَندي مَي، أنا مِش عَطشان.", romanization: "3andi may, ana mísh 3aTshaan.", altRomanizations: [], english: "I have water, I am not thirsty.", direction: "both", grammarNote: null },
    { id: "l10-s-025", lessonId: 10, type: "sentence", arabic: "أنا جُوعان. في أكِل هون؟", romanization: "ana juu3aan. fii akíl hoon?", altRomanizations: [], english: "I am hungry, is there food here?", direction: "both", grammarNote: null },
    { id: "l10-s-026", lessonId: 10, type: "sentence", arabic: "صَباح الخير ماما. بِدِّك قَهوة؟ / لاء يا إبني، بِدّي شاي.", romanization: "Sabaa7 íl-kheer maama. bíddek 2ahwe? / La2 ya íbni, bíddi shaay.", altRomanizations: [], english: "Good morning mom, Do you (f) want coffee? / No, my son, I want tea.", direction: "both", grammarNote: "Cheatsheet numbers this two-line exchange as a single item; see l10-p-035/l10-p-036 for the split phrase entries and l10-d-004 pattern for the exchange as a mini-dialogue." },
    { id: "l10-s-027", lessonId: 10, type: "sentence", arabic: "الصَّبِيّة جُوعانة، بِدّها أكِل.", romanization: "íS-Sabiyye juu3aane, bídda akíl.", altRomanizations: ["íS-Sabiyye juu3aane. bídha akíl."], english: "The young lady is hungry, she wants food.", direction: "both", grammarNote: "Cheatsheet spells \"she wants\" as bídda (North-leaning) vs. bídha on the Example Phrases page (l10-p-037) — same N/S \"she wants\" contrast documented elsewhere; both accepted." },
    { id: "l10-s-028", lessonId: 10, type: "sentence", arabic: "اي، عِنّا ولاد، عِنّا صَبي وبِنت.", romanization: "eh, 3ínna wlaad. 3ínna Sabi u-bínt.", altRomanizations: [], english: "Yes, we have kids, we have a boy and a girl.", direction: "both", grammarNote: null },
    { id: "l10-s-029", lessonId: 10, type: "sentence", arabic: "الصَّبي إللي لابِس كَنزة زَرقَة كتير تَعبان.", romanization: "íS-Sabi ílli laabís kanze zar2a ktiir ta3baan.", altRomanizations: [], english: "The boy that's wearing a blue t-shirt is very tired.", direction: "both", grammarNote: null },
    { id: "l10-s-030", lessonId: 10, type: "sentence", arabic: "الصَّبِيّة إللي فِالسَّيّارَة هناك، حِلوة كتير.", romanization: "íS-Sabiyye ílli fís-sayyara hnaak, 7ilwe ktiir.", altRomanizations: [], english: "The young lady that's in the car over there is very pretty.", direction: "both", grammarNote: null },
    { id: "l10-s-031", lessonId: 10, type: "sentence", arabic: "الكَلب إللي فِالبيت كتير كِبير.", romanization: "íl-kalb ílli fíl-beet ktiir kbiir.", altRomanizations: [], english: "The dog that's in the house is very big.", direction: "both", grammarNote: null },
    { id: "l10-s-032", lessonId: 10, type: "sentence", arabic: "الأوضَة إللي هنيك كتير كِبيرة.", romanization: "íl-uuDa ílli hniik ktiir kbiire.", altRomanizations: [], english: "The room that's over there is very big.", direction: "both", grammarNote: null },
    { id: "l10-s-033", lessonId: 10, type: "sentence", arabic: "عِنّا كَنابايَة سودا فِأوضِة القَعدة.", romanization: "3ínna kanabaaye sooda fi-ooDet íl-2a3de.", altRomanizations: [], english: "We have a black couch in the living room.", direction: "both", grammarNote: null },
    { id: "l10-s-034", lessonId: 10, type: "sentence", arabic: "ما بِدُّن الصُّوفايَة إللي بِأوضِة النَّوم.", romanization: "maa bíddun íS-Suufaaye ílli bi-uuDet ín-noom.", altRomanizations: [], english: "They don't want the couch that's in the bed room.", direction: "both", grammarNote: null }
  ],
  dialogues: [
    {
      id: "l10-d-001",
      lessonId: 10,
      lines: [
        { speaker: "A", arabic: "تشَرَّفنا", romanization: "tsharrafna", english: "Pleasure to meet you." },
        { speaker: "B", arabic: "الشَّرَف إلي", romanization: "ísh-sharaf íli", english: "The pleasure is mine." },
        { speaker: "A", arabic: "تشَرَّفنا (أكتَر)", romanization: "tsharrafna aktar", english: "Pleasure to meet you (more)." }
      ],
      relatedItemIds: ["l10-p-045", "l10-p-046", "l10-p-047"]
    },
    {
      id: "l10-d-002",
      lessonId: 10,
      lines: [
        { speaker: "A", arabic: "تِصبَح على خير", romanization: "tíSba7 3ala kheer", english: "Goodnight." },
        { speaker: "B", arabic: "وإنت بخير", romanization: "w-ínta b-kheer", english: "Goodnight to you." },
        { speaker: "B", arabic: "وإنت مِن أهلُه", romanization: "w-ínte mín ahlu", english: "And may you be good (more poetic alternate reply)." }
      ],
      relatedItemIds: ["l10-p-048", "l10-p-049", "l10-p-050"]
    },
    {
      id: "l10-d-003",
      lessonId: 10,
      lines: [
        { speaker: "A", arabic: "أخُوك هون؟", romanization: "akhuuk hoon?", english: "Is your (m) brother here?" },
        { speaker: "B", arabic: "لاء، هُوّ فِالبيت.", romanization: "la2, huwwe fíl-beet.", english: "No, he is at home." }
      ],
      relatedItemIds: ["l10-g-004", "l10-g-005", "l10-g-006", "l10-g-007", "l10-p-010"]
    },
    {
      id: "l10-d-004",
      lessonId: 10,
      lines: [
        { speaker: "A", arabic: "بِدكُم قَهوة؟", romanization: "bídkum 2ahwe?", english: "Do you (pl) want coffee?" },
        { speaker: "B", arabic: "لاء، شُكراً.", romanization: "la2, shukran.", english: "No, thanks." }
      ],
      relatedItemIds: ["l10-g-008", "l10-g-009", "l10-g-010", "l10-p-026"]
    }
  ]
};
